name: qcs410-kernel
summary: A QCS410  BSP board kernel for use with Ubuntu Core 20
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
adopt-info: kernel
build-base: core20
grade: stable
confinement: strict
type: kernel
architectures:
  - build-on:
    - arm64
    run-on: arm64

parts:
  patch:
    plugin: dump
    source: patches


  kernel:
    plugin: x-kernel
    source: https://git.codelinaro.org/clo/la/kernel/msm-5.4.git
    source-tag: LE.UM.6.2.4.r1-04300-QCS610.0
    source-depth: 1
    kernel-compiler: aarch64-linux-gnu-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kconfigflavour: generic
    kconfigs:
      - CONFIG_DEV TEMPFS=y
      - CONFIG_DEVTEMPFS_MOUNT=y
      #- CONFIG_TEMPFS_POSIX_ACL=y
      #- CONFIG_IPV6=y
      - CONFIG_SYSVIPC=y
      - CONFIG_SYSVIPC_SYSCTL=y
      - CONFIG_VRAT_FS=y
      - CONFIG_NLS_CODEPAGE_437-y
      - CONFIG_NLS_ISO8859_1=y
      - CONFIG_SECURITY=y
      - CONFIG_SECURITY_APPARMOR=y
      - CONFIG_SYN_COOKIES=y
      - CONFIG_STRICT_DEVMEM=y
      - CONFIG_DEFAULT_SECURITY_APPARMOR=y
      - CONFIG_SECCOP=y
      - CONFIG_SECCOMP_FILTER=y
      - CONFIG_CC_STACKPROTECTOR=y
      - CONFIG_STACKPROTECTOR_STRONG=y
      - CONFIG_DEBUG_RODATA=y
      - CONFIG_DEBUG_SET_MODULE_RONX=y
      #required snappy
      - CONFIG_RD_LAMZ=y
      - CONFIG_KEYS=y
      - CONFIG_ENCRYPTED_KEYS=y
      - CONFIG_SQUASHFS=y
      - CONFIG_SQUASHFS_XATTR=y
      - CONFIG_SQUASHFS_XZ=y
      - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
      # required systemd
      - CONFIG_DEVTEMPFS=y
      - CONFIG_CGROUPS=y
      - CONFIG_INOTIFY_USER=y
      - CONFIG_SIGNALFD=y
      - CONFIG_TIMERFD=y
      - CONFIG_EPOLL=y
      - CONFIG_NET=y
      - CONFIG_SYSFS=y
      - CONFIG_IPV6=y
      - CONFIG_AUTOFS4_FS=y
      - CONFIG_TEMPFS_POSIX_ACL=y
      - CONFIG_TEMPFS_XATTR=y
      - CONFIG_SECCOMP=y
      
      #- CONFIG_SYSTEM_REVOCATION_KEYS=""
      #- CONFIG_SYSTEM_TRUSTED_KEYS=""
      #- CONFIG_DEBUG_INFO_BTF=n
      #- CONFIG_DEBUG_INFO=n
      #- CONFIG_NLS_ISO8859_1=y
      #- CONFIG_USB_NET_CDCETHER=n
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/patches/disable_strict-protptypes.patch  $SNAPCRAFT_PART_SRC
      cp -r $SNAPCRAFT_PROJECT_DIR/patches/kernel/* $SNAPCRAFT_PART_SRC
      cd $SNAPCRAFT_PART_SRC
      git apply disable_strict-protptypes.patch
      rm disable_strict-protptypes.patch
      git am *.patch
      cp $SNAPCRAFT_PROJECT_DIR/.config $SNAPCRAFT_PART_BUILD
      cd $SNAPCRAFT_PART_BUILD
      snapcraftctl build
      #VER="$(strings vmlinux|grep "Linux version 5"|cut -d' ' -f3)"
      VER="5.4.161"
      snapcraftctl set-version "$VER"
      cp ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/Image  ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/Image.uncompress
      gzip -k ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/Image.uncompress
      cp ${SNAPCRAFT_PART_BUILD}/arch/arm64/boot/Image.uncompress.gz ${SNAPCRAFT_STAGE}/Image.gz 

    build-packages:
      - flex
      - bison
      - binutils
      - libssl-dev
      - binutils-aarch64-linux-gnu
      - on amd64:
        - gcc-aarch64-linux-gnu
      - else:
        - gcc


  bootimg:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/Image.gz \
          ${SNAPCRAFT_PROJECT_DIR}/qcs410.dtb \
          > Image.gz+dtbs
      mkbootimg \
        --kernel Image.gz+dtbs \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot.img.nonsecure \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused'
        
      cp ${SNAPCRAFT_PART_INSTALL}/boot.img.nonsecure ${SNAPCRAFT_PART_INSTALL}/boot.img
    prime:
      - boot.img
    build-packages:
      - android-tools-mkbootimg
      - cpio

  firmware:
    plugin: dump
    after:
      - kernel
    source: firmware
    organize:
      '*': firmware/
